// Korean for every string the plugin shows; English is the key. Unit names come from the editor as they are.
// `tests/ko.test.ts` fails on a `t("…")` or `msg("…")` in the source with no entry here, and on an entry nothing uses.
export const KO: Record<string, string> = {
  "(minitile {x}, {y})": "(미니타일 {x}, {y})",
  "+ {n} under {size} tiles": "+ {size}타일 미만 {n}개",
  "+ {n} wider": "+ 더 넓은 것 {n}개",
  "Analyse": "분석",
  "Analyse walkability": "이동 가능 지형 분석",
  "Area {n}": "구역 {n}",
  "Area {n}: {size} tiles": "구역 {n}: {size}타일",
  "Areas": "구역",
  "Areas and chokes": "구역과 길목",
  "Between start locations": "시작 위치 사이",
  "Between start locations (tiles)": "시작 위치 사이 (타일)",
  "Buildings and resources block the way": "건물과 자원이 길을 막음",
  "Chokes": "길목",
  "Chokes (narrowest first)": "길목 (좁은 순)",
  "Chokes up to": "길목 최대 폭",
  "Clearance (room to move)": "여유 폭 (움직일 공간)",
  "Click an area": "구역을 클릭하세요",
  "Click an island": "섬을 클릭하세요",
  "Click to go there": "클릭하면 그곳으로 이동",
  "Copy a text summary to the clipboard": "텍스트 요약을 클립보드에 복사합니다",
  "Copy report": "보고서 복사",
  "Copy walkability report": "이동 가능 지형 보고서 복사",
  "Details…": "자세히…",
  "Every start location, pair, island, area and choke in a panel of its own": "모든 시작 위치, 시작 위치 쌍, 섬, 구역, 길목을 별도 패널에 보여 줍니다",
  "Ground as flagged": "플래그 그대로의 땅",
  "Ground height and seams": "지면 높이와 이음매",
  "Height seam at {x}, {y}: height {from} meets {to} with no ramp": "{x}, {y}의 높이 이음매: 높이 {from}과(와) {to}이(가) 경사로 없이 맞닿습니다",
  "Height seams (a unit can walk between ground heights with no ramp)": "높이 이음매 (유닛이 경사로 없이 높이 사이를 걸어 다닐 수 있는 곳)",
  "Island {n}": "섬 {n}",
  "Island {n}: {patches, plural, one {# patch} other {# patches}}, {geysers, plural, one {# geyser} other {# geysers}}": "섬 {n}: 미네랄 {patches}개, 가스 간헐천 {geysers}개",
  "Island {n}: {size} tiles": "섬 {n}: {size}타일",
  "Island {n}: {size} tiles, {who}": "섬 {n}: {size}타일, {who}",
  "Islands (largest first)": "섬 (큰 순)",
  "Islands and pockets": "섬과 고립 지대",
  "Labels": "라벨",
  "Large units (Siege Tank, Ultralisk)": "대형 유닛 (시즈 탱크, 울트라리스크)",
  "Medium units (Dragoon, Hydralisk)": "중형 유닛 (드라군, 히드라리스크)",
  "Min. area": "최소 구역",
  "Move the pointer over the map.": "포인터를 맵 위로 옮기세요.",
  "No areas.": "구역이 없습니다.",
  "No passage up to {n} tiles wide between areas.": "구역 사이에 폭 {n}타일 이하의 통로가 없습니다.",
  "No walkable ground.": "이동 가능한 땅이 없습니다.",
  "None found.": "발견된 문제가 없습니다.",
  "Opacity": "불투명도",
  "Open a map first.": "먼저 맵을 여세요.",
  "Overlay": "오버레이",
  "Pick an area on the map": "맵에서 구역 고르기",
  "Player {n}": "플레이어 {n}",
  "Press Analyse, or switch the overlay on, to read the map.": "맵을 읽으려면 분석을 누르거나 오버레이를 켜세요.",
  "Problems": "문제",
  "Reading the map again…": "맵을 다시 읽는 중…",
  "Reading the map…": "맵을 읽는 중…",
  "Reading…": "읽는 중…",
  "Resources off the main ground": "주 지형 밖의 자원",
  "Seams": "이음매",
  "Small units (Marine, Zergling)": "소형 유닛 (마린, 저글링)",
  "Start locations": "시작 위치",
  "Start locations are on {n} different islands": "시작 위치가 서로 다른 섬 {n}개에 있습니다",
  "The map has no start locations.": "맵에 시작 위치가 없습니다.",
  "The overlay is off.": "오버레이가 꺼져 있습니다.",
  "The overlay stays on while you work on any layer and follows every edit; View ▸ Walkability, the Layers panel or {key} switch it off and on.": "오버레이는 어느 레이어에서 작업하든 켜진 채로 모든 편집을 따라갑니다. 보기 ▸ 이동 가능 지형, 레이어 패널, {key}로 끄고 켭니다.",
  "Unit size": "유닛 크기",
  "Walkability": "이동 가능 지형",
  "Walkability details": "이동 가능 지형 자세히",
  "Walkability overlay": "이동 가능 지형 오버레이",
  "Walkability: loading the tileset…": "이동 가능 지형: 타일셋을 불러오는 중…",
  "Walkability: open a map first": "이동 가능 지형: 먼저 맵을 여세요",
  "Walkability: report copied": "이동 가능 지형: 보고서를 복사했습니다",
  "Walkability: the browser refused the clipboard": "이동 가능 지형: 브라우저가 클립보드 사용을 거부했습니다",
  "Walkability: the tileset graphics are not available, so there are no minitile flags to read": "이동 가능 지형: 타일셋 그래픽이 없어 읽을 미니타일 플래그가 없습니다",
  "Walkability: {error}": "이동 가능 지형: {error}",
  "Walkability: {islands, plural, one {# island} other {# islands}}, {areas, plural, one {# area} other {# areas}}, {chokes, plural, one {# choke} other {# chokes}}, {seams, plural, one {# height seam} other {# height seams}} ({ms} ms)": "이동 가능 지형: 섬 {islands}개, 구역 {areas}개, 길목 {chokes}개, 높이 이음매 {seams}개 ({ms} ms)",
  "Walkability: {islands, plural, one {# island} other {# islands}}, {areas, plural, one {# area} other {# areas}}, {chokes, plural, one {# choke} other {# chokes}}, {seams, plural, one {# height seam} other {# height seams}} in {ms} ms": "이동 가능 지형: 섬 {islands}개, 구역 {areas}개, 길목 {chokes}개, 높이 이음매 {seams}개, {ms} ms",
  "Walkability…": "이동 가능 지형…",
  "Walkable ground": "이동 가능한 땅",
  "air {air} · ground {ground} · {width} wide": "공중 {air} · 지상 {ground} · 폭 {width}",
  "air {air} · no ground route": "공중 {air} · 지상 경로 없음",
  "area {a} ↔ {b}": "구역 {a} ↔ {b}",
  "ground {ground}, narrowest {width} wide": "지상 {ground}, 가장 좁은 곳 폭 {width}",
  "hall spot not buildable": "본진 건물 자리에 지을 수 없음",
  "height seam: no ramp here": "높이 이음매: 여기에는 경사로가 없음",
  "height {n}": "높이 {n}",
  "height {n}, ramp": "높이 {n}, 경사로",
  "island {island} · area {area}": "섬 {island} · 구역 {area}",
  "island {n}": "섬 {n}",
  "island {n}, {area}": "섬 {n}, {area}",
  "narrowest: {n} tiles": "가장 좁은 곳: {n}타일",
  "no ground route": "지상 경로 없음",
  "no ground route from a start": "시작 위치에서 가는 지상 경로 없음",
  "no ramp": "경사로 없음",
  "no start location": "시작 위치 없음",
  "no start location reaches it": "닿는 시작 위치 없음",
  "not on walkable ground": "이동 가능한 땅 위가 아님",
  "off the ground": "땅 밖",
  "out of date": "최신 아님",
  "tiles": "타일",
  "tiles wide": "타일 폭",
  "under a building": "건물 아래",
  "unreachable": "닿을 수 없음",
  "unwalkable": "이동 불가",
  "walkable, but too tight for the chosen unit size ({n} tiles from a wall)": "이동 가능하지만 고른 유닛 크기에는 너무 좁음 (벽에서 {n}타일)",
  "walkable, {n} tiles from the nearest wall": "이동 가능, 가장 가까운 벽에서 {n}타일",
  "{a} – {b}: air {air}, {ground}": "{a} – {b}: 공중 {air}, {ground}",
  "{islands, plural, one {# island} other {# islands}}, {areas, plural, one {# area} other {# areas}}, {chokes, plural, one {# choke} other {# chokes}}, {seams, plural, one {# height seam} other {# height seams}}": "섬 {islands}개, 구역 {areas}개, 길목 {chokes}개, 높이 이음매 {seams}개",
  "{n, plural, one {# choke} other {# chokes}}": "길목 {n}개",
  "{n, plural, one {# resource} other {# resources}} with no walkable ground around them (first: {name} at {x}, {y})": "주위에 이동 가능한 땅이 없는 자원 {n}개 (첫 번째: {x}, {y}의 {name})",
  "{n} minitiles": "미니타일 {n}개",
  "{patches, plural, one {# mineral field} other {# mineral fields}} and {geysers, plural, one {# geyser} other {# geysers}} on island {n}: no start location reaches them by ground": "섬 {n}의 미네랄 필드 {patches}개와 가스 간헐천 {geysers}개: 지상으로 닿는 시작 위치가 없습니다",
  "{patches, plural, one {# mineral field} other {# mineral fields}} and {geysers, plural, one {# geyser} other {# geysers}} with no walkable ground around them: no start location reaches them by ground": "주위에 이동 가능한 땅이 없는 미네랄 필드 {patches}개와 가스 간헐천 {geysers}개: 지상으로 닿는 시작 위치가 없습니다",
  "{player} at {x}, {y}": "{x}, {y}의 {player}",
  "{player} at {x}, {y}: {where}": "{x}, {y}의 {player}: {where}",
  "{player}'s start location is not on walkable ground": "{player}의 시작 위치가 이동 가능한 땅 위에 있지 않습니다",
  "{player}'s town hall spot is not buildable": "{player}의 본진 건물 자리에 지을 수 없습니다",
  "{player}: the town hall spot is not buildable": "{player}: 본진 건물 자리에 지을 수 없습니다",
  "{size} minitiles at {x}, {y}: height {from} meets {to}": "{x}, {y}의 미니타일 {size}개: 높이 {from}과(와) {to}이(가) 맞닿음",
  "{size} tiles, {chokes, plural, one {# choke} other {# chokes}}": "{size}타일, 길목 {chokes}개",
  "{width} tiles wide at {x}, {y}": "{x}, {y}의 폭 {width}타일",
  "{width} tiles wide at {x}, {y} between {a} and {b}": "{a}와(과) {b} 사이, {x}, {y}의 폭 {width}타일",
};
